source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "minimal-mistakes-jekyll", path: ".."
gem "rake"

gem "tzinfo-data"
gem "wdm", "~> 0.1.0" if Gem.win_platform?

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-paginate", "1.1.0"
  gem "jekyll-sitemap", "1.4.0"
  gem "jekyll-gist", "1.5.0"
  gem "jekyll-feed", "0.13.0"
  gem "jemoji", "0.11.1"

  gem "jekyll-include-cache", "~> 0.2"
  gem "jekyll-algolia", "~> 1.6"
end
